minor update

diff --git a/functions/_diskguard_cp b/functions/_diskguard_cp
--- a/functions/_diskguard_cp
+++ b/functions/_diskguard_cp
@@ -104,7 +104,23 @@ _diskguard_cp() {
     # We need to enable a trap for ^C so that we can call 'tput cnorm'
     # and the cursor will become visible again when ^C is pressed.
     # ──────────────────────────────────────────────────────────────
-    trap '_diskguard_deinit_term; tput cnorm 2>/dev/null; printf "\n\n  ^C – operation cancelled\n\n"; return 1' INT
+    interrupted=false
+    trap '_diskguard_deinit_term; tput cnorm 2>/dev/null; interrupted=true' INT TERM
+
+    for ((i = 0; i < 100; ++i)); do
+        clear
+        date
+        sleep 1
+
+        if [[ "${interrupted}" = "true" ]]; then
+            printf '%s\n' " → Ctrl+C was pressed – operation cancelled"; return 1
+            break
+        fi
+    done
+
+    # TRAPINT()   { diskguard_cleanup; }
+    # TRAPTERM()  { TRAPINT; }
+    TRAPWINCH() { clear; col=$(tput cols); lines_raw=$(tput lines); }
 
     # Disable job control messages temporarily
     setopt LOCAL_OPTIONS NO_NOTIFY NO_MONITOR
